name: Mise à jour de l'ATIS
on:
  schedule:
    - cron: '22,52 * * * *'
  workflow_dispatch:

jobs:
  update-atis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ATIS_TOKEN }}
          fetch-depth: 1

      - name: Installer ffmpeg/curl (optimisé)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends ffmpeg curl

      - name: Cache Whisper model
        uses: actions/cache@v3
        with:
          path: ~/.cache/whisper
          key: whisper-model-small-${{ hashFiles('**/process_atis.py') }}

      - name: Installer Whisper (modèle small)
        run: pip install git+https://github.com/openai/whisper.git

      - name: Enregistrer l'ATIS (45s max)
        run: |
          curl -s -A "Mozilla/5.0" -e "https://www.liveatc.net/" "https://s1-fmt2.liveatc.net/eetn2_atis" | \
          ffmpeg -i pipe:0 -t 90 -y atis_tallinn.mp3

      - name: Transcrire avec Whisper (modèle small)
        run: whisper atis_tallinn.mp3 --model small --language English --output_format txt

      - name: Post-traitement ATIS
        run: python3 process_atis.py atis_tallinn.txt > atis_structured.html

      - name: Mettre à jour index.html
        run: |
          cp index.html index.html.bak
          awk 'BEGIN { in_div = 0 } {
            if ($0 ~ /<div id="atis-message">/) {
              print $0;
              while (getline line < "atis_structured.html") print line;
              close("atis_structured.html");
              in_div = 1;
            } else if ($0 ~ /<\/div>/ && in_div) {
              print $0;
              in_div = 0;
            } else if (!in_div) print $0;
          }' index.html.bak > index.html

      - name: Commit & Push (si changements)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          if ! git diff-index --quiet HEAD; then
            git commit -m "ATIS Update: $(date +'%Y-%m-%d %H:%M:%S')"
            git push -f https://valoch29:${{ secrets.ATIS_TOKEN }}@github.com/valoch29/ReadATIS.git HEAD:main
          fi
