name: Mise à jour automatique de l'ATIS

on:
  schedule:
    - cron: '22,52 * * * *'  # Exécute 2 fois par heure
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  update-atis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install git+https://github.com/openai/whisper.git requests pydub

      - name: Enregistrer le flux ATIS avec Python
        run: |
          python3 - <<EOF
          import requests
          from pydub import AudioSegment
          import io

          url = "http://www.liveatc.net/hlisten.php?mount=eetn2_atis&icao=eetn"
          response = requests.get(url, stream=True)

          with open("atis_tallinn.mp3", "wb") as f:
              for chunk in response.iter_content(chunk_size=1024):
                  if chunk:
                      f.write(chunk)
          EOF

      - name: Transcrire l'audio avec Whisper
        run: |
          whisper atis_tallinn.mp3 --model base --language English --output_format txt --output_dir .

      - name: Mettre à jour index.html avec la transcription
        run: |
          transcription=$(cat atis_tallinn.txt)
          sed -i "s|<div id=\"atis-message\">.*</div>|<div id=\"atis-message\"><p>$transcription</p></div>|" index.html

      - name: Valider et pousser les modifications
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Mise à jour automatique de l'ATIS : $(date)"
          git push
