name: Mise à jour automatique de l'ATIS

on:
  schedule:
    - cron: '0,30 * * * *'  # Exécute 2 fois par heure
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  update-atis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Enregistrer le flux ATIS avec ffmpeg
        run: |
          ffmpeg -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
                 -headers "Referer: https://www.liveatc.net/" \
                 -i "https://s1-fmt2.liveatc.net/eetn2_atis" \
                 -t 60 \
                 -y atis_tallinn.mp3

      - name: Installer Whisper
        run: |
          pip install git+https://github.com/openai/whisper.git

      - name: Transcrire l'audio avec Whisper
        run: |
          whisper atis_tallinn.mp3 --model base --language English --output_format txt --output_dir .

      - name: Mettre à jour index.html avec la transcription
        run: |
          transcription=$(cat atis_tallinn.txt)
          sed -i "s|<div id=\"atis-message\">.*</div>|<div id=\"atis-message\"><p>$transcription</p></div>|" index.html

      - name: Valider et pousser les modifications
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Mise à jour automatique de l'ATIS : $(date)"
          git push
