name: Mise à jour automatique de l'ATIS (modèle finetuné)
on:
  schedule:
    - cron: '22,52 * * * *'  # Exécution toutes les heures à 22 et 52 minutes
  workflow_dispatch:         # Permet un déclenchement manuel

jobs:
  update-atis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ATIS_TOKEN }}

      - name: Créer un fichier .gitignore
        run: |
          echo "atis_tallinn.mp3" >> .gitignore
          echo "atis_tallinn.txt" >> .gitignore
          echo "whisper-atis.pt" >> .gitignore

      - name: Installer les dépendances système
        run: |
          sudo apt update
          sudo apt install -y ffmpeg curl wget perl

      - name: Configurer le cache Python
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Installer Whisper et télécharger le modèle finetuné ATIS
        run: |
          pip install git+https://github.com/openai/whisper.git
          # Télécharger le modèle finetuné pour l'ATIS
          wget https://huggingface.co/skytemple/whisper-medium-atc/resolve/main/model.pt -O /tmp/whisper-atis.pt

      - name: Enregistrer le flux ATIS avec curl et ffmpeg
        run: |
          curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
               -e "https://www.liveatc.net/" \
               "https://s1-fmt2.liveatc.net/eetn2_atis" | \
          ffmpeg -i pipe:0 -t 60 -y atis_tallinn.mp3

      - name: Transcrire avec le modèle finetuné ATIS
        run: |
          whisper atis_tallinn.mp3 \
            --model medium \
            --language English \
            --output_format txt \
            --output_dir . \
            --fp16 False \
            --model_path /tmp/whisper-atis.pt
          # Post-traitement avancé pour standardiser le format ATIS
          sed -i -e 's/ degrees/°/g' \
                 -e 's/ kilo[^ ]* meters/km/g' \
                 -e 's/ Celsius/°C/g' \
                 -e 's/ transition level/Transition Level/g' \
                 -e 's/ QNH \([0-9]\{4\}\)/QNH \1 hPa/g' \
                 -e 's/\([0-9]\) \([0-9]\)/\1\2/g' \
                 -e 's/\([0-9]\),\([0-9]\)/\1\2/g' \
                 -e 's/\([0-9]\)\([0-9]\)\([0-9]\)°/\1\2\3°/g' \
                 -e 's/ATIS information \([A-Z]\)/ATIS information \1:/g' \
                 atis_tallinn.txt
          # Afficher la transcription finale
          echo "Transcription finale :"
          cat atis_tallinn.txt

      - name: Mettre à jour index.html avec la transcription
        run: |
          if [ -f atis_tallinn.txt ]; then
            # Échapper les caractères spéciaux pour HTML
            transcription=$(cat atis_tallinn.txt | tr '\n' ' ' | sed -e 's/"/\\&quot;/g' -e "s/'/\\&#39;/g")
            # Créer une copie de sauvegarde
            cp index.html index.html.bak
            # Utiliser awk pour une substitution robuste
            awk -v trans="$transcription" '
            BEGIN { in_div = 0 }
            {
              if ($0 ~ /<div id="atis-message">/) {
                print $0
                print "        <p>" trans "</p>"
                in_div = 1
              }
              else if ($0 ~ /<\/div>/ && in_div) {
                print $0
                in_div = 0
              }
              else if (!in_div) {
                print $0
              }
            }' index.html.bak > index.html
            # Afficher le résultat pour vérification
            echo "Contenu mis à jour dans index.html :"
            grep -A5 "<div id=\"atis-message\">" index.html
          else
            echo "Erreur : le fichier atis_tallinn.txt est manquant." >&2
            exit 1
          fi

      - name: Valider et pousser les modifications
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          # Vérifier s'il y a des changements
          if git diff-index --quiet HEAD; then
            echo "Aucun changement détecté dans index.html."
          else
            timestamp=$(date +"%Y-%m-%d %H:%M:%S")
            git commit -m "Mise à jour ATIS Tallinn (modèle finetuné) : $timestamp"
            git push https://valoch29:${{ secrets.ATIS_TOKEN }}@github.com/valoch29/ReadATIS.git HEAD:main
          fi
