name: Mise à jour automatique de l'ATIS

on:
  schedule:
    - cron: '22,52 * * * *'  # Exécute chaque heure à 22 et 52 minutes
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  update-atis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: |
          sudo apt update
          sudo apt install -y ffmpeg curl

      - name: Enregistrer le flux ATIS avec curl et ffmpeg
        run: |
          curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
               -e "https://www.liveatc.net/" \
               "https://s1-fmt2.liveatc.net/eetn2_atis" | \
          ffmpeg -i pipe:0 -t 60 -y atis_tallinn.mp3

      - name: Installer Whisper
        run: |
          pip install git+https://github.com/openai/whisper.git

      - name: Transcrire l'audio avec Whisper
        run: |
          whisper atis_tallinn.mp3 --model base --language English --output_format txt --output_dir .

      - name: Nettoyer et mettre à jour index.html avec la transcription
        run: |
          if [ -f atis_tallinn.txt ]; then
            # Nettoyer les caractères spéciaux
            transcription=$(cat atis_tallinn.txt | sed 's/[\/&]/\\&/g')
            # Utiliser une approche alternative pour éviter les problèmes avec sed
            awk -v trans="$transcription" '{
              if ($0 ~ /<div id="atis-message">.*<\/div>/){
                print "<div id=\"atis-message\"><p>" trans "</p></div>"
              } else {
                print $0
              }
            }' index.html > index_new.html && mv index_new.html index.html
          else
            echo "Le fichier de transcription n'existe pas."
            exit 1
          fi

      - name: Valider et pousser les modifications
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Mise à jour automatique de l'ATIS : $(date)"
          git push
